Controllers/LivroController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Bibliotec.Contexts;
using Bibliotec.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Bibliotec_mvc.Controllers
{
    [Route("[controller]")]
    public class LivroController : Controller
    {
        private readonly ILogger<LivroController> _logger;

        public LivroController(ILogger<LivroController> logger)
        {
            _logger = logger;
        }

        Context context = new Context();

        public IActionResult Index()
        {
            ViewBag.Admin = HttpContext.Session.GetString("Admin")!;

            //Criar uma lista de livros
            List<Livro> listaLivros = context.Livro.ToList();

            //Verificar se o livro tem reserva ou nao
            var livrosreservados = context.LivroReserva.ToDictionary(livro => livro.LivroID, livror => livror.DtReserva);

            ViewBag.livros = listaLivros;
            ViewBag.LivroComReserva = livrosreservados;


            return View();
        }

        [Route("Cadastro")]
        //Metodo que aparece/retorna a tela de cadastro
        public IActionResult Cadastro()
        {

            ViewBag.Admin = HttpContext.Session.GetString("Admin")!;

            ViewBag.Categorias = context.Categoria.ToList();
            //Retorna a View de cadastro
            return View();
        }

        //Metodo para cadastrar um livro
        [Route("Cadastrar")]
        public IActionResult Cadastrar(IFormCollection form)
        {

            Livro novoLivro = new Livro();
            //O que meu usuario escrever no formulario sera atribuido ao novoLivro

            novoLivro.Nome = form["Nome"].ToString();
            novoLivro.Descricao = form["Descricao"].ToString();
            novoLivro.Editora = form["Editora"].ToString();
            novoLivro.Escritor = form["Escritor"].ToString();
            novoLivro.Idioma = form["Idioma"].ToString();
            //Trabalha com imagens
            if (form.Files.Count > 0)
            {
                //Primeiro passo:
                //Armazenarmos o arquivo enviado pelo usuario
                var arquivo = form.Files[0];

                //Segundo passo:
                //Criar variavel do caminho da minha pasta para colocar as fotos dos livros 
                var pasta = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/Livros");
                //Validarmos se a pasta que sera armazenada as imagens, existe. Caso nao exista, criaremos uma nova pasta.
                if (!Directory.Exists(pasta))
                {
                    //criar a pasta:
                    Directory.CreateDirectory(pasta);
                }
                //Terceiro passo:
                //Criar a variavel para armazenar o caminho em que meu arquivo estara, alem do nome dele
                var caminho = Path.Combine(pasta, arquivo.FileName);

                using (var stream = new FileStream(caminho, FileMode.Create))
                {
                    //Copiou o arquivo para o meu diretorio
                    arquivo.CopyTo(stream);
                }

                novoLivro.Imagem = arquivo.FileName;
            }
            else
            {
                novoLivro.Imagem = "padrao.png";
            }

            context.Livro.Add(novoLivro);
            context.SaveChanges();

            //SEGUNDA PARTE: E adicionar dentro de LivroCategoria que pertence ao novoLivro
            //Listar as categorias

            List<LivroCategoria> listaLivroCategorias = new List<LivroCategoria>();

            //Array que possui as categorias selecionadas pelo usuarrio
            string[] categoriasSelecionadas = form["Categoria"].ToString().Split(',');
            //Acao, terror,suspense

            foreach (string categoria in categoriasSelecionadas)
            {
                //string categoria possui a informacao do ID da c ategoreia ATUAL selecionada
                LivroCategoria livroCategoria = new LivroCategoria();

                livroCategoria.CategoriaID = int.Parse(categoria);
                livroCategoria.LivroID = novoLivro.LivroID;
                //Adicionamos o obj livroCategoria dentro da lista listaLivrosCategorias
                listaLivroCategorias.Add(livroCategoria);
            }
            //Peguei a colecao da listaLivrosCategorias
            context.LivroCategoria.AddRange(listaLivroCategorias);

            context.SaveChanges();

            return LocalRedirect("/Cadastro");
        }

        [Route("Editar/{id}")]
        public IActionResult Editar(int id ){

            ViewBag.Admin = HttpContext.Session.GetString("Admin")!;

            ViewBag.CategoriasDoSistema = context.Categoria.ToList();

            

            // LivroID == 3

            // Buscar quem e o tal do id numero 3:
            Livro livroAtualizado = context.Livro.FirstOrDefault(livro => livro.LivroID == id)!;

            //Buscar as categorias que o livroAtualizado possui 
            var categoriasDoLivroEncontrado = context.LivroCategoria.Where(identificadorLivro => identificadorLivro.LivroID == id).Select(livro => livro.Categoria).ToList();

            //Quero pegar as informacoes do meu livro selecionado e mandar para a minha View
            ViewBag.Livro = livroAtualizado;
            ViewBag.Categoria = categoriasDoLivroEncontrado;


            return View();
        }

        //Metodo que atualiza as informacoes do livro
        [Route ("Atualizar/{id}")]
        public IActionResult Atualizar(IFormCollection form, int id, IFormFile imagem){
            //Buscar o livro especifico peloID
            Livro livroAtualizado = context.Livro.FirstOrDefault(livro => livro.LivroID == id)!;

            livroAtualizado.Nome = form ["Nome"].ToString();
            livroAtualizado.Escritor = form["Escritor"];
            livroAtualizado.Editora = form["Editora"];
            livroAtualizado.Idioma = form["Idioma"];
            livroAtualizado.Descricao = form["Descricao"];

            //Upload de imagem
            if(imagem ! = null && imagem.Length > 0){

                //Definir o caminho da minha imagem do livro atual que eu quero alterar:
                var caminhoImagem = Path.Combine("wwwroot/images/Livros", imagem.FileName);

                //Verificar se o usuario colocou uma imagem para atualizar o livro
                if(string.IsNullOrEmpty (livroAtualizado.Imagem)){
                    //Caso exista, ela ira ser apagada 
                    var caminhoImagemAntiga = Path.Combine("wwwroot/images/Livros", livroAtualizado.Imagem);
                    //Ver ser existe uma imagem no caminho antigo
                    if(System.IO.File.Exists(caminhoImagemAntiga)){
                        System.IO.File.Delete(caminhoImagemAntiga);
                    }
                }

                //Salvar a imagem nova
                using(var stream = new FileStream(caminhoImagem, FileMode.Create)){
                    imagem.CopyTo(stream);
                }

                //Subir essa mudanca para o meu banco de deaos
                livroAtualizado.Imagem = imagem.FileName;

            }

            //CATEGORIAS:

            //PRIMEIRO: Precisamos pegar as categorias selecionadas do usuario
            var categoriasSelecionadas = form["Categoria"].ToList();
            //SEGUNDO: Pegaremos as categorias ATUAIS do livro
            var categoriasAtuais = context. LivroCategoria.Where(livro => livro.LivroID == id).ToList();
            //TERCEIRO: Removermos as categorias antigas
            foreach(var categoria in categoriasAtuais){
                if(!categoriasSelecionadas.Contains(categoria.CategoriaID.ToString())){
                    //Nos vamos resolver a categoria do nosso context
                    context.LivroCategoria.Remove(categoria);
                }                                                                                                               
            }
            //QUARTO: Adicionaremos as novas categorias 
            foreach(var categoria in categoriasSelecionadas){
                //Verificando se nao existe a categoria nesse livro
                if(!categoriasAtuais.Any(c => c.CategoriaID.ToString() == categoria)){
                    context.LivroCategoria.Add(new LivroCategoria{
                        LivroID = id,
                        CategoriaID = int.Parse(categoria)
                    });
                }
            }

            context.SaveChanges();

            return LocalRedirect("/Livro");

        }

        //METODO DE EXCLUIR O LIVRO
        [Route("Excluir")]
        public IActionResult Excluir(int id){
            //Buscar qual o livro do id que precisamos exluir
            Livro livroEncontrado = context.Livro.First(livro => livro.LivroID == id);

            //Buscar as categorias desse livro:
            var categoriasDoLivro = context.LivroCategoria.Where(livro => livro.LivroID == id).ToList();

            //Precisa excluir primeiro o registro da tabela intermediaria
            foreach(var categoria in categoriasDoLivro){
                context.LivroCategoria.Remove(categoria);
            }

            context.Livro.Remove(livroEncontrado);

            context.SaveChanges();

            return LocalRedirect("/Livro");
        }


        // [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        // public IActionResult Error()
        // {
        //     return View("Error!");
        // }
    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Bibliotec.Contexts;
using Bibliotec.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Bibliotec.Controllers
{
    [Route("[controller]")]
    public class LoginController : Controller
    {
        private readonly ILogger<LoginController> _logger;

        public LoginController(ILogger<LoginController> logger)
        {
            _logger = logger;
        }

        Context context = new Context();

        public IActionResult Index()
        {
            return View();
        }

        [Route("Logar")]
        public IActionResult Logar(IFormCollection form){
            // Criar duas variaveis para armazenar as informacoes do formulario
            string emailInformado = form["Email"].ToString();
            string senhaInformado = form["Senha"].ToString();

            // Busca no banco de dados
            Usuario usuarioBuscado = context.Usuario.FirstOrDefault(usuario => usuario.Email == emailInformado && usuario.Senha == senhaInformado)!;

            // De outra forma:
            //Criei uma lista de usuários
            // List<Usuario> listaUsuario = context.Usuario.ToList();

            // foreach(Usuario usuario_ in listaUsuario){
            //     if(usuario_.Email == emailInformado && usuario_.Senha == senhaInformado){
            //         //Usuario logado
            //     }else{
            //         //Usuario nao encontrado
            //     }
            // }

            //Se meu usuario buscado for igual a nulo
            if(usuarioBuscado == null){
                Console.WriteLine($"Dados inválidos!");
                return LocalRedirect("~/Login");
            }else{
                Console.WriteLine($"Eba você entrou!");
                HttpContext.Session.SetString("UsuarioID", usuarioBuscado.UsuarioID.ToString());
                HttpContext.Session.SetString("Admin", usuarioBuscado.Admin.ToString());
                return LocalRedirect("~/Usuario");
            }
        }

        // [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        // public IActionResult Error()
        // {
        //     return View("Error!");
        // }

    }
}

Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Bibliotec.Contexts;
using Bibliotec.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Bibliotec_mvc.Controllers
{
    [Route("[controller]")]
    public class UsuarioController : Controller
    {
        private readonly ILogger<UsuarioController> _logger;

        public UsuarioController(ILogger<UsuarioController> logger)
        {
            _logger = logger;
        }

        //Criando um obj da classe Context:
        Context context = new Context();

        //O metodo esta retornando a view Usuario/Index.cshtml
        public IActionResult Index()
        {
            //pegar as informacoes da session para que apareca os detalhes do meu usuario:
            int id = int.Parse (HttpContext.Session.GetString("UsuarioID")!);
            ViewBag.Admin = HttpContext.Session.GetString("Admin")!;

            //busquei o usuario que esta logado (beatriz)
            Usuario usuarioEncontrado = context.Usuario.FirstOrDefault(usuario => usuario.UsuarioID == id)!;
            //se mao for encontrado ninguem
            if(usuarioEncontrado == null){
                return NotFound();
            }

            //procurar o curso que meu usuarioEncontrado esta cadastrado
            Curso cursoEncontrado = context.Curso.FirstOrDefault(curso => curso.CursoID == usuarioEncontrado.CursoID)!;

            //Verificar se o usuario possui ou nao o curso
            if(cursoEncontrado ==  null){
                //O usuario nao possui curso cadastrado
                ViewBag.Curso = "O usuario nao possui curso cadastrado";
            }else{
                //o usuario possui o curso XXX
                ViewBag.Curso = cursoEncontrado.Nome;
            }

            ViewBag.Nome = usuarioEncontrado.Nome;
            ViewBag.Email = usuarioEncontrado.Email;
            ViewBag.Contato = usuarioEncontrado.Contato;
            ViewBag.DtNascimento = usuarioEncontrado.DtNascimento.ToString("dd/MM/yyyy");



            return View();
        }


        // [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        // public IActionResult Error()
        // {
        //     return View("Error!");
        // }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
     <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bibliotec</title>
    <link rel="icon" type="image/png" sizes="32x32" href="~/images/logo-mobile.png">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Bibliotec.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/menulateral.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bibliotec.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

</head>

<body>
    @if(ViewBag.Admin == "False"){
        //Menu de aluno
        <div class="container-flex">
            <div class="sombra"></div>
            <aside class="">
                <span onclick="recolheMenu(event);" class="mnu-arrow-left">&lt;</span>
                <div class="aside-top">
                    <img class="logo-mobile" src="~/images/logo-mobile.png" alt="" />

                    <nav class="menu-lateral">
                        <a href="#" class="nav-item-active">
                            <img src="~/images/UserPlus-icon.svg" alt="" />
                            Perfil
                        </a>

                        <a href="#">
                            <img src="~/images/Book-icon.png" alt="" />
                            Livros Disponíveis
                        </a>
                        <a href="#">
                            <img src="~/images/BookHeart-Icon.png" alt="" />
                            Favoritos
                        </a>
                    </nav>
                </div>

                <a class="user-logout" asp-area="" asp-controller="Login" asp-action="Logout">
                    <img src="~/images/logout-icon.svg" alt="" />
                    Sair
                </a>
            </aside>

            @RenderBody()
        </div>
    
    }else if (ViewBag.Admin == "True"){
        //Menu do admin
        <div class="container-flex">
            <div class="sombra"></div>
            <aside class="">
                <span onclick="recolheMenu(event);" class="mnu-arrow-left">&lt;</span>
                <div class="aside-top">
                    <img class="logo-mobile" src="~/images/logo-mobile.png" alt="" />

                    <nav class="menu-lateral">
                        <a class="nav-item-active" asp-area="" asp-controller="Usuario" asp-action="Index" >
                            <img src="~/images/UserPlus-icon.svg" alt="Icone de usuário com um símbolo de adição"/>
                            Perfil
                        </a>
                        <a asp-area="" asp-controller="Livro" asp-action="Cadastro">
                            <img src="~/images/CadLivro-icon.png" alt="Icone de livro com um símbolo de adição" />
                            Cadastrar Livro
                        </a>
                        <a asp-area="" asp-controller="Livro" asp-action="Index">
                            <img src="~/images/ListLivro-icon.png" alt="ícone com três livros" />
                            Listar Livros
                        </a>

                    </nav>
                </div>

                <a class="user-logout" asp-area="" asp-controller="Login" asp-action="Logout">
                    <img src="~/images/logout-icon.svg" alt="" />
                    Sair
                </a>
            </aside>

            @RenderBody()
        </div>
    
    }else {
        <!-- ************ CABEÇALHO ************ -->
        <header class="header">
        <div class="container header-flex">
            <img src="~/images/logo-recortado.png" alt=""
                class="logotipo. Imagem de um libro aberto e um texto escrito Bibliotech" />
            <nav class="navbar" id="navbar">
                <img class="arrow-left" src="~/images/arrow-left.svg" alt="Menu Mobile" onclick="mostraMenu()" />
                <img class="logo-mobile" src="~/images/logo-mobile.png" alt="Menu Mobile" />
                <a asp-controller="Login" asp-action="Index" class="navbar-item">Login</a>
            </nav>

            <img src="~/images/menu-hamburger.png" alt="" class="menu-hamburger" id="menu-hamburger"
                onclick="mostraMenu()" />
        </div>
    </header>

    @* <div class="container">
        <main role="main" class="pb-3"> *@
            @RenderBody()
        @* </main>
    </div> *@

<footer class="footer">
        <div class="container footer-flex">

            <div class="footer-logo">
                <img class="images-footer-logo" src="~/images/logo-desktop.svg" alt="" />
                <img class="images-footer-senai" src="~/images/logo-senai-vermelho.png" alt="" />
            </div>

            <nav class="footer-nav">

                <div class="left-info">
                    <h4>Biblioteca</h4>
                    <a href="#">Baixar aplicativo</a>
                    <a href="#">Suporte ao usuário</a>
                    <h4 class="sociais-titulo">Siga nas redes sociais</h4>
                </div>

                <div class="right-info">
                    <h4>Quem somos</h4>
                    <a href="#">Clientes</a>
                    <a href="#">Benefícios</a>
                    <span class="sociais">
                        <a href="#"><img src="~/images/facebook-icon.png" alt=""></a>
                        <a href="#"><img src="~/images/instagram-icon.png" alt=""></a>
                        <a href="#"><img src="~/images/linkedin-icon.png" alt=""></a>
                    </span>
                </div>
            </nav>
        </div>

        <div class="container footer-mobile-only">
            <p class="right">
                &copy; 2024 Bibliotec - Todos os direitos reservados
            </p>
        </div>
    </footer>
    }

    <script src="~/scripts/index.js"></script>
 
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>